name: Deploy to EC2

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /app

            git pull origin main

            export IMAGE_TAG=${{ github.sha }}

            docker compose -f docker-compose.prod.yaml pull 
            docker compose -f ./docker-compose.prod.yaml up -d --remove-orphans
            docker image prune -f

            curl --fail http://localhost/api/v1/health
