name: Deploy to EC2

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            APP_DIR="/app"

            if [ ! -d "$APP_DIR" ]; then
              echo "CHECKING APPLICATION DIRECTORY..."
              sudo mkdir -p "$APP_DIR"
              sudo chown ubuntu:ubuntu "$APP_DIR"
            fi

            if [ ! -d "$APP_DIR/.git" ]; then
              echo "REPOSITORY NOT FOUND. CLONING..."

              git clone https://github.com/${{ github.repository }} "$APP_DIR"
            else
              echo "REPOSITORY EXISTS. PULLING LATEST CHANGES..."

              cd "$APP_DIR"
              git fetch origin
              git reset --hard origin/main
            fi

            cd "$APP_DIR"

            echo "CREATING ENV FILES..."

            cat > .env.backend.prod <<EOF
            PORT=${{ secrets.PORT }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            POSTGRES_DB=${{ secrets.DATABASE_DB }}
            POSTGRES_USER=${{ secrets.DATABASE_USER }}
            POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            EOF

            cat > .env.frontend.prod <<EOF
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            EOF

            export IMAGE_TAG=${{ github.sha }}

            echo "PULLING LATEST IMAGES..."
            docker compose -f docker-compose.prod.yaml pull 

            echo "STARTING CONTAINERS..."
            docker compose -f ./docker-compose.prod.yaml up -d --remove-orphans

            docker compose ps

            docker compose logs backend --tail=100

            docker inspect backend --format='{{.State.ExitCode}} {{.State.Error}}'

            echo "CLEANING OLD IMAGES..."
            docker image prune -f

            sleep 15

            echo "RUNNING HEALTH CHECK..."
            curl --fail http://localhost/api/v1/health

            echo "DEPLOYMENT COMPLETED SUCCESSFULLY..."
